# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c70514fc2a53a39f33515176c71b12400ef51d8e570cf23978bb440e47f8e4ae70f1e4775cb75148d77c5742af5c1487072fd0503ea0718647f97522cea1d0c8

test:
  secret_key_base: 16f73b0f72bae6e872bd93b0f37b0d427bd15718e82bc1f2f57755495fe4d76a8da9ff7fb9605bffc2efa09bdd387d629dc8bfa46169a7c0a8577d5568359a5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
